package com.moodjournal.service;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import com.moodjournal.model.JournalEntry;
import org.springframework.stereotype.Service;
import java.io.ByteArrayOutputStream;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.time.format.DateTimeFormatter;
import java.util.List;

@Service
public class ExportService {

    private static final DateTimeFormatter DATE_FMT = DateTimeFormatter.ofPattern("yyyy-MM-dd");

    // ===== PDF Export =====

    public byte[] generatePdf(List<JournalEntry> entries) throws Exception {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        Document document = new Document(PageSize.A4, 50, 50, 60, 60);
        PdfWriter.getInstance(document, baos);
        document.open();

        // Title
        Font titleFont = new Font(Font.FontFamily.HELVETICA, 22, Font.BOLD,
                new BaseColor(91, 143, 191));
        Paragraph title = new Paragraph("🌿 My Mood Journal", titleFont);
        title.setAlignment(Element.ALIGN_CENTER);
        document.add(title);

        Font subtitleFont = new Font(Font.FontFamily.HELVETICA, 11, Font.NORMAL,
                new BaseColor(107, 122, 141));
        Paragraph subtitle = new Paragraph("Exported on " + java.time.LocalDate.now().format(DATE_FMT) +
                " | " + entries.size() + " entries", subtitleFont);
        subtitle.setAlignment(Element.ALIGN_CENTER);
        subtitle.setSpacingAfter(20);
        document.add(subtitle);

        // Table
        PdfPTable table = new PdfPTable(4);
        table.setWidthPercentage(100);
        table.setWidths(new float[]{1.8f, 1.5f, 2.0f, 5.0f});
        table.setSpacingBefore(10);

        // Header
        addTableHeader(table, "Date");
        addTableHeader(table, "Mood");
        addTableHeader(table, "Tags");
        addTableHeader(table, "Journal Notes");

        // Rows
        Font cellFont = new Font(Font.FontFamily.HELVETICA, 9, Font.NORMAL, BaseColor.DARK_GRAY);
        Font moodFont = new Font(Font.FontFamily.HELVETICA, 9, Font.BOLD, new BaseColor(91, 143, 191));

        boolean even = false;
        for (JournalEntry entry : entries) {
            BaseColor rowBg = even ? new BaseColor(248, 249, 252) : BaseColor.WHITE;

            addTableCell(table, entry.getDate() != null ? entry.getDate().format(DATE_FMT) : "", cellFont, rowBg);
            addTableCell(table, entry.getMood() != null ? entry.getMood() : "", moodFont, rowBg);
            addTableCell(table, entry.getTags() != null ? entry.getTags() : "", cellFont, rowBg);

            String text = entry.getText() != null ? entry.getText() : "";
            if (text.length() > 200) text = text.substring(0, 200) + "...";
            addTableCell(table, text, cellFont, rowBg);

            even = !even;
        }

        document.add(table);

        // Footer note
        Font footerFont = new Font(Font.FontFamily.HELVETICA, 8, Font.ITALIC, BaseColor.GRAY);
        Paragraph footer = new Paragraph("\nGenerated by MoodJournal — Track your emotions, grow your mind.", footerFont);
        footer.setAlignment(Element.ALIGN_CENTER);
        document.add(footer);

        document.close();
        return baos.toByteArray();
    }

    private void addTableHeader(PdfPTable table, String text) {
        Font headerFont = new Font(Font.FontFamily.HELVETICA, 10, Font.BOLD, BaseColor.WHITE);
        PdfPCell cell = new PdfPCell(new Phrase(text, headerFont));
        cell.setBackgroundColor(new BaseColor(91, 143, 191));
        cell.setPadding(8);
        cell.setBorder(Rectangle.NO_BORDER);
        table.addCell(cell);
    }

    private void addTableCell(PdfPTable table, String text, Font font, BaseColor bg) {
        PdfPCell cell = new PdfPCell(new Phrase(text, font));
        cell.setPadding(6);
        cell.setBorder(Rectangle.BOTTOM);
        cell.setBorderColor(new BaseColor(224, 232, 240));
        cell.setBorderWidth(0.5f);
        cell.setBackgroundColor(bg);
        table.addCell(cell);
    }

    // ===== CSV Export =====

    public byte[] generateCsv(List<JournalEntry> entries) {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        PrintWriter writer = new PrintWriter(new OutputStreamWriter(baos, StandardCharsets.UTF_8));

        // UTF-8 BOM for Excel compatibility
        writer.print('\uFEFF');
        writer.println("Date,Mood,Tags,Text");

        for (JournalEntry entry : entries) {
            String date = entry.getDate() != null ? entry.getDate().format(DATE_FMT) : "";
            String mood = entry.getMood() != null ? entry.getMood() : "";
            String tags = entry.getTags() != null ? entry.getTags() : "";
            String text = entry.getText() != null ? entry.getText().replace("\"", "\"\"") : "";

            writer.printf("\"%s\",\"%s\",\"%s\",\"%s\"%n", date, mood, tags, text);
        }

        writer.flush();
        return baos.toByteArray();
    }
}
